# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2.1
orbs:
  aws-s3: circleci/aws-s3@1.0.15
jobs:
  build:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/jringstad/osprey/platform-diagnostics
    steps:
      - checkout:
          path: /go/src/github.com/jringstad/osprey/
      - run: GOARCH=arm GOOS=linux go build platform-diagnostics.go
      - run: ./make-deb
      - run: tar -cf platform-diagnostics.tar platform-diagnostics misc
      - run: bzip2 platform-diagnostics.tar
      - persist_to_workspace:
          root: /go/src/github.com/jringstad/osprey/platform-diagnostics
          paths:
            - platform-diagnostics.tar.bz2

  publish-github-release:
    docker:
      - image: circleci/golang:1.9
    working_directory: /tmp/workspace/
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - aws-s3/copy:
          from: platform-diagnostics.tar.bz2
          to: 's3://osprey-groundstation/binaries/'
          arguments: |
            --acl public-read

workflows:
  version: 2
  build-and-publish-diagnostics:
    jobs:
      - build
      - publish-github-release:
          requires:
            - build
