# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2.1
orbs:
  aws-s3: circleci/aws-s3@1.0.15

workflows:
  main:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
      - publish-github-release:
          requires:
            - build
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
jobs:
  build:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/jringstad/osprey/
    steps:
      - checkout:
          path: /go/src/github.com/jringstad/osprey/
      - run: cd bootstrapper && GOARCH=arm GOOS=linux go build bootstrapper.go
      - run: cd autossh && GOARCH=arm GOOS=linux go build autossh.go
      - run: cd platform/low-level-control-service && GOARCH=arm GOOS=linux go build -o osprey-low-level-control-service main.go
      - persist_to_workspace:
          root: /go/src/github.com/jringstad/
          paths:
            - osprey

  publish-github-release:
    docker:
      - image: ruby:2.4.2-jessie-slim
    working_directory: /tmp/workspace/osprey/
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run: cd bootstrapper/debian && bash -x make-deb $CIRCLE_TAG
      - run: cd autossh/debian && bash -x make-deb $CIRCLE_TAG
      - run: gem install deb-s3
      - run: cd bootstrapper/debian && deb-s3 upload osprey-bootstrapper-$CIRCLE_TAG.deb --bucket osprey-groundstation --preserve-versions --s3-region=${AWS_REGION}
      - run: cd autossh/debian && deb-s3 upload osprey-autossh-$CIRCLE_TAG.deb --bucket osprey-groundstation --preserve-versions --s3-region=${AWS_REGION}
      - run: cd platform/low-level-control-service/debian && deb-s3 upload osprey-low-level-control-service-$CIRCLE_TAG.deb --bucket osprey-groundstation --preserve-versions --s3-region=${AWS_REGION}
      - run: cd platform/metapackage/debian && deb-s3 upload osprey-platform-$CIRCLE_TAG.deb --bucket osprey-groundstation --preserve-versions --s3-region=${AWS_REGION}
