# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2.1
orbs:
  aws-s3: circleci/aws-s3@1.0.15
jobs:
  build:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/jringstad/osprey/platform-diagnostics
    steps:
      - checkout:
          path: /go/src/github.com/jringstad/osprey/
      - run: go build platform-diagnostics.go
      - store_artifacts:
          path: platform-diagnostics
          destination: artifact-file

  publish-github-release:
    docker:
      - image: circleci/golang:1.9
    working_directory: ~/artifacts/
    steps:
      - attach_workspace:
          at: ~/artifacts/
      - run: pwd
      - run: ls
      - aws-s3/copy:
          from: platform-diagnostics
          to: 's3://osprey-groundstation/binaries/'

workflows:
  version: 2
  build_and_publish_diagnostics:
    jobs:
      - build
      - publish-github-release:
          requires:
            - build
          filters:
            tags:
              only: /^\d+\.\d+\.\d+$/
            branches:
              only: master
