# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2.1
orbs:
  aws-s3: circleci/aws-s3@1.0.15
jobs:
  build:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/jringstad/osprey/platform-diagnostics
    steps:
      - checkout:
          path: /go/src/github.com/jringstad/osprey/
      - run: GOARCH=arm GOOS=linux go build platform-diagnostics.go
      - persist_to_workspace:
          root: /go/src/github.com/jringstad/
          paths:
            - osprey

  publish-github-release:
    docker:
      - image: circleci/ruby:2.4.2-jessie-node
    working_directory: /tmp/workspace/osprey/platform-diagnostics/
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run: ./make-deb $CIRCLE_TAG
      - run: gem install deb-s3
      - run: deb-s3 upload osprey-diagnostics-$CIRCLE_TAG.deb --bucket osprey-groundstation --preserve-versions --s3-region=${AWS_REGION}

workflows:
  version: 2
  build-and-publish-diagnostics:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - publish-github-release:
          requires:
            - build
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
